### ISSUE TITLE
Missing DebugLog.log exception

### ISSUE THREAD

**Issue by tkosan** [AustinGilkison/Evolutionary-Network.py#2]
When I try to run the program, I receive the following exception:

``
Evolutionary-Network.py$ python Run.py 
Traceback (most recent call last):
  File "Run.py", line 1, in <module>
    import Core
  File "/home/tkosan/git2/Evolutionary-Network.py/Core.py", line 4, in <module>
    import Population
  File "/home/tkosan/git2/Evolutionary-Network.py/Population.py", line 14, in <module>
    filemode='w')
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/tkosan/git2/Evolutionary-Network.py/Logs/DebugLog.Log'
``

What should I do to fix this problem?

**Comment by AustinGilkison** [comment]
Are you running this is a Linux, windows, mac environment?
Also, could you please try using python3.6 You will also need Tkinter You'll have to use yum or apt-get python3-tk

Also, try running GUI.py instead

**Comment by AustinGilkison** [comment]
Also, try running GUI.py 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ted Kosan <notifications@github.com> Date: 8/20/18  1:57 PM  (GMT-05:00) To: "AustinGilkison/Evolutionary-Network.py" <Evolutionary-Network.py@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [AustinGilkison/Evolutionary-Network.py] Missing DebugLog.log exception (#2) 
When I try to run the program, I receive the following exception:
Evolutionary-Network.py$ python Run.py Traceback (most recent call last): File "Run.py", line 1, in <module> import Core File "/home/tkosan/git2/Evolutionary-Network.py/Core.py", line 4, in <module> import Population File "/home/tkosan/git2/Evolutionary-Network.py/Population.py", line 14, in <module> filemode='w') File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig hdlr = FileHandler(filename, mode) File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__ StreamHandler.__init__(self, self._open()) File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open stream = open(self.baseFilename, self.mode) IOError: [Errno 2] No such file or directory: '/home/tkosan/git2/Evolutionary-Network.py/Logs/DebugLog.Log'
What should I do to fix this problem?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AustinGilkison/Evolutionary-Network.py","title":"AustinGilkison/Evolutionary-Network.py","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AustinGilkison/Evolutionary-Network.py"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Missing DebugLog.log exception (#2)"}],"action":{"name":"View Issue","url":"https://github.com/AustinGilkison/Evolutionary-Network.py/issues/2"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AustinGilkison/Evolutionary-Network.py/issues/2",
"url": "https://github.com/AustinGilkison/Evolutionary-Network.py/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Missing DebugLog.log exception (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Ted Kosan**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@tkosan",
"facts": [
{
"name": "Repository: ",
"value": "AustinGilkison/Evolutionary-Network.py"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"AustinGilkison/Evolutionary-Network.py\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"AustinGilkison/Evolutionary-Network.py\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/AustinGilkison/Evolutionary-Network.py/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 370264835\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by tkosan** [comment]
I am running Linux. I did a `git pull`, ran `python3 GUI.py`, and it worked.
